import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx,js,jsx,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        error: "#ffb4ab",
        "surface-container-lowest": "#0c0e11",
        outline: "#8f9378",
        "primary-container": "#caf300",
        "tertiary-fixed": "#ffdadb",
        "inverse-on-surface": "#2f3034",
        "error-container": "#93000a",
        "secondary-container": "#00a6e0",
        "secondary-fixed-dim": "#7bd0ff",
        secondary: "#7bd0ff",
        "outline-variant": "#444932",
        background: "#111317",
        "surface-tint": "#b0d500",
        "inverse-primary": "#536600",
        "on-primary-container": "#596c00",
        "secondary-fixed": "#c4e7ff",
        "on-primary": "#2a3400",
        "on-tertiary-container": "#c51640",
        "on-tertiary": "#67001b",
        "surface-container-low": "#1a1c1f",
        "on-primary-fixed-variant": "#3e4c00",
        "on-secondary-fixed-variant": "#004c69",
        surface: "#111317",
        "on-surface-variant": "#c5c9ac",
        "on-secondary-container": "#00374d",
        "on-secondary-fixed": "#001e2c",
        "tertiary-fixed-dim": "#ffb2b7",
        "surface-container": "#1e2023",
        "surface-container-highest": "#333538",
        "surface-variant": "#333538",
        "surface-container-high": "#282a2d",
        "tertiary-container": "#ffdadb",
        "on-error-container": "#ffdad6",
        "surface-dim": "#111317",
        primary: "#ffffff",
        "surface-bright": "#37393d",
        "primary-fixed-dim": "#b0d500",
        "on-surface": "#e2e2e6",
        "on-tertiary-fixed-variant": "#92002a",
        tertiary: "#ffffff",
        "primary-fixed": "#caf300",
        "on-background": "#e2e2e6",
        "on-tertiary-fixed": "#40000d",
        "on-primary-fixed": "#171e00",
        "on-error": "#690005",
        "inverse-surface": "#e2e2e6",
        "on-secondary": "#00354a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        gutter: "1rem",
        margin: "1rem",
      },
      fontFamily: {
        "body-md": ["Inter", "system-ui", "sans-serif"],
        "label-sm": ["Inter", "system-ui", "sans-serif"],
        "headline-lg": ["Inter", "system-ui", "sans-serif"],
        "label-numeric": ["Inter", "system-ui", "sans-serif"],
        "headline-md": ["Inter", "system-ui", "sans-serif"],
        caption: ["Inter", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "system-ui", "sans-serif"],
        "display-hero": ["Inter", "system-ui", "sans-serif"],
        "headline-sm": ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-numeric": ["18px", { lineHeight: "22px", letterSpacing: "0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "30px", letterSpacing: "-0.015em", fontWeight: "700" }],
        caption: ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "display-hero": ["48px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
      animation: {
        "ping-slow": "ping 2.5s cubic-bezier(0, 0, 0.2, 1) infinite",
      },
    },
  },
  plugins: [],
};

export default config;